language: php

php:
  - 5.6.12
  - 5.6.13
  - 5.6.14
  - 5.6.15
  - 5.6.16
  - 5.6.17
  - 5.6.18
  - 5.6.19
  - 5.6.23
  - 5.6.24
  - 5.6.25
  - 5.6.26
  - 5.6.27
  - 5.6.28
  - 5.6.29
  - 5.6.30
  - 7.0
  - 7.1
  - hhvm

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --prefer-source --no-interaction

script: vendor/phpunit/phpunit/phpunit --verbose
